### ISSUE TITLE
Vimeo Video Player Not Working

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#184]
For some reason, the vimeo videos are not playing on zume5.training.

**Comment by squigglybob** [comment]
Is this fixed now? @ChrisChasm The ones i just checked on home page and session 1 worked fine

**Comment by ChrisChasm** [comment]
Yes. I ended up just changing the global embed permissions on all vimeo. It was something they changed on their side that was failing to recognized approved domain names. So I just moved away from that permission.
