### ISSUE TITLE
Home: Vimeo Video play features reduced

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#211]
The home page video and maybe others that are available to the public, need to be reduced to simply a play button. 
Remove the full screen, window in window, and player bar. 
Maybe leave the closed captions and transcripture, if it does not look cluttered.
Basically moving the appearance to be more simple and design focused.

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/ee658c0f8f6e5111a86bebef67879f52/screenshot/5e6dc75c-f835-4587-898e-a0667dde1cc9.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/ee658c0f8f6e5111a86bebef67879f52/screenshot/0a0a9088-c14e-40a0-a122-4555ef0e3ef9.png)

-------------------------------------

**Website URL:**
[https://zume5.training/](https://zume5.training/)

**Device and browser info:**
Chrome 123.0.6312.87 (2547x1504) | Mac OS (arm) 10.15.7

**Date and time:**
April 2nd 2024 | 5:53pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/59043c35-d2bf-4ed5-89ff-3b0c4f3292fe](https://jam.dev/c/59043c35-d2bf-4ed5-89ff-3b0c4f3292fe)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
I've used the parameters available on this page https://help.vimeo.com/hc/en-us/articles/12426260232977-Player-parameters-overview
to remove
* player in picture
* transcription
and removed the allowFullscreen parameter from the iframe remove the fullscreen button.

@ChrisChasm is the main issue what it looks like before it starts playing?
If so we could maybe cover over the iframes with a fade on click cover with a design that better matches the site

**Comment by ChrisChasm** [comment]
I think this concern is closed for now. When we do a final proof pass on the entire site for GoLive, we can let this issue come back up if it is a real one.

**Comment by squigglybob** [comment]
Would you like me to merge in the PR which reduces the controls on all videos everywhere to be like this image?
![image](https://github.com/ZumeProject/zume-training-system/assets/9816214/98dd2aa2-2c46-4116-908c-65bdd8daca40)
