### ISSUE TITLE
Training: CSS not working on list content

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#214]
The items under Needed for the training and NOT needed for the training should be bullet point lists, but there is no styling inheriting for the UL and LI elements.

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/670a063df88eb38c12841837a68655ed/screenshot/f4a89946-0f59-42cb-9d01-d57fd090652b.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/670a063df88eb38c12841837a68655ed/screenshot/78d198a0-118b-491f-9664-d870c079cdf6.png)

-------------------------------------

**Website URL:**
[https://zume5.training/training/](https://zume5.training/training/)

**Device and browser info:**
Chrome 123.0.6312.87 (2547x1504) | Mac OS (arm) 10.15.7

**Date and time:**
April 2nd 2024 | 7:24pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/a72b8a94-7210-41d0-8117-6cb7fac9436c](https://jam.dev/c/a72b8a94-7210-41d0-8117-6cb7fac9436c)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
fixed in 0db84cd
