### ISSUE TITLE
Share: Descriptions are off by one

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#216]
The description below the titles are off by one.

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/8e74acb7e35fe13035b6483941f1f5b3/screenshot/c381f651-9eda-4e30-950a-6b22d9df5c59.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/8e74acb7e35fe13035b6483941f1f5b3/screenshot/b12a1f01-5d0a-47fa-b793-677e042f3e7a.png)

-------------------------------------

**Website URL:**
[https://zume5.training/share](https://zume5.training/share)

**Device and browser info:**
Chrome 123.0.6312.87 (2411x1349) | Mac OS (arm) 10.15.7

**Date and time:**
April 2nd 2024 | 7:39pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/15bf17e9-448c-4aaf-a17c-8a6153890a34](https://jam.dev/c/15bf17e9-448c-4aaf-a17c-8a6153890a34)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
fixed in b378883
