### ISSUE TITLE
Remove: Assess Someone

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#240]
Remove second paragraph

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/e956636e3166099530edb6a7a7ea2983/screenshot/6d99526a-1610-4e22-82bf-fdbbab9423e0.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/e956636e3166099530edb6a7a7ea2983/screenshot/d521e5ea-41f6-41e0-8196-00af1b432e82.png)

-------------------------------------

**Website URL:**
[https://zume5.training/en/zume_app/translator?tab=slides&type=10&session=0](https://zume5.training/en/zume_app/translator?tab=slides&type=10&session=0)

**Device and browser info:**
Chrome 123.0.6312.107 (1727x1219) | Mac OS (arm) 10.15.7

**Date and time:**
April 9th 2024 | 2:17pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/51846f14-0dfe-4e8c-aef8-e3632878297c](https://jam.dev/c/51846f14-0dfe-4e8c-aef8-e3632878297c)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
Completed
