### ISSUE TITLE
Slides: Content too long

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#242]
Can the width of the template change to fit the longer content.

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/0db25ca0df8b1be58fba02c95124e5ec/screenshot/74ecf0b3-d8e8-4a2d-a293-0a72c8cfc7e9.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/0db25ca0df8b1be58fba02c95124e5ec/screenshot/257851e2-0b1d-4418-b511-0b306b8fa8a6.png)

-------------------------------------

**Website URL:**
[https://zume5.training/en/zume_app/translator?tab=slides&type=10&session=0](https://zume5.training/en/zume_app/translator?tab=slides&type=10&session=0)

**Device and browser info:**
Chrome 123.0.6312.107 (1727x1219) | Mac OS (arm) 10.15.7

**Date and time:**
April 9th 2024 | 2:37pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/e6cdcedf-4a76-41b6-9c0e-dc03ac35a5e7](https://jam.dev/c/e6cdcedf-4a76-41b6-9c0e-dc03ac35a5e7)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
I've been thinking about stepping back the font size maybe?
On the slides with 2 columns there won't be space to increase the width, so those one's will have to have reduced font-size or something to make sure they fit on ok
