### ISSUE TITLE
Top Bar: Move to full width

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#284]
It looks like the top blue bar has been limited to max-width. I think it should be full width. 
The body is full width, it looks good. I think the zume logo being inset does not look good.

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/1f424df3851c7831d53d923baae285c2/screenshot/5c2628aa-35ab-4647-9338-104c1e564ca2.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/1f424df3851c7831d53d923baae285c2/screenshot/8d7b4eb0-4bf7-452a-8d58-a7a49d4480f0.png)

-------------------------------------

**Website URL:**
[https://zume5.training/dashboard/](https://zume5.training/dashboard/)

**Device and browser info:**
Chrome 123.0.6312.124 (2054x2763) | Mac OS (arm) 10.15.7

**Date and time:**
April 17th 2024 | 12:25pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/46c5e7ba-d1aa-46b4-ac6c-a13b4d1491b1](https://jam.dev/c/46c5e7ba-d1aa-46b4-ac6c-a13b4d1491b1)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
@ChrisChasm 
Agreed.  it doesn't look great.
I think I added it in to make it look better somewhere else 😆 

I'll have another look at it
