### ISSUE TITLE
The activity resource link works, but the coaching checklist page is still blank

### ISSUE THREAD

**Issue by glo-ria368** [ZumeProject/zume-training-system#286]
**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/00ac95a0e1fb39d0bbfaf7ee2b621ea7/screenshot/9e3d784b-672d-4d67-bbae-c7ebf9cc8afa.png)

-------------------------------------

**Website URL:**
[https://zume5.training/presenter?type=20&session=17&view=slideshow](https://zume5.training/presenter?type=20&session=17&view=slideshow)

**Device and browser info:**
Chrome 123.0.6312.58 (1440x754) | Mac OS (x86) 10.15.7

**Date and time:**
April 18th 2024 | 10:18am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/29fc69ae-887d-440e-89ed-7c3674fdd8a2](https://jam.dev/c/29fc69ae-887d-440e-89ed-7c3674fdd8a2)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
Currently the coaching checklist is not developed.

I will create a ticket and link it here that we will track the creation of this checklist on.

#291 
#292
