### ISSUE TITLE
Add spacing to activity resource

### ISSUE THREAD

**Issue by glo-ria368** [ZumeProject/zume-training-system#287]
The four fiels activity resource link works, but when I pull the link up on my phone, it comes up as one big text block. Suggest adding spacing to make it easier to read

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/f511cd56ea3e98b5671825c4dfd837b7/screenshot/799c125a-dd5d-431b-b5f6-b7a131606c01.png)

-------------------------------------

**Website URL:**
[https://zume5.training/presenter?type=20&session=18&view=slideshow](https://zume5.training/presenter?type=20&session=18&view=slideshow)

**Device and browser info:**
Chrome 123.0.6312.58 (1440x754) | Mac OS (x86) 10.15.7

**Date and time:**
April 18th 2024 | 10:21am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/978e64fc-e63e-4580-ae36-cc435654e6d6](https://jam.dev/c/978e64fc-e63e-4580-ae36-cc435654e6d6)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
@glo-ria368 Yup, that shouldn't be a big block of text on that one.
Good spot
