### ISSUE TITLE
Activity resource is hard to read

### ISSUE THREAD

**Issue by glo-ria368** [ZumeProject/zume-training-system#289]
Link for activity resource works. The peer mentoring groups page is a big text block that is hard to read, suggest adding spacing

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/621daf7e98a986c1adf22db770f997b4/screenshot/ed61a63f-387e-4e1e-b00d-cc14a3be6a23.png)

-------------------------------------

**Website URL:**
[https://zume5.training/presenter?type=20&session=19&view=slideshow](https://zume5.training/presenter?type=20&session=19&view=slideshow)

**Device and browser info:**
Chrome 123.0.6312.58 (1440x754) | Mac OS (x86) 10.15.7

**Date and time:**
April 18th 2024 | 10:24am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/f90e29c8-9093-4e2a-9266-3e4c25c238ce](https://jam.dev/c/f90e29c8-9093-4e2a-9266-3e4c25c238ce)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
@glo-ria368 thanks for sifting through the presenter to find any issues with it.
Could you add some screenshots in comments to this ticket to help describe the blocks of text you are seeing.
Thanks 😄

**Comment by squigglybob** [comment]
Sorry, was looking at it locally on my computer, where the spacing is still there.
It looks like the formatting has been lost for all of the activities.
They will look prettier once the formatting is back

**Comment by squigglybob** [comment]
All fixed
