### ISSUE TITLE
Unneeded Translation of the Word Zume into local text.  

### ISSUE THREAD

**Issue by CE-Taiwan** [ZumeProject/zume-training-system#297]
Use the English word for Zume in front of the equal sign, followed by the local language meaning.

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/1438a1131c1e249bce6c192c53a66b6e/screenshot/614ee3c4-4264-490a-8981-d2178cd228f1.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/1438a1131c1e249bce6c192c53a66b6e/screenshot/b6f0f77c-b314-45dd-8274-e88e2a3916a4.png)

-------------------------------------

**Website URL:**
[https://zume5.training/zhtw/](https://zume5.training/zhtw/)

**Device and browser info:**
Chrome 124.0.6367.62 (1551x996) | Mac OS (arm) 10.15.7

**Date and time:**
April 23rd 2024 | 8:48am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/4664a1f2-b622-40e3-bb1a-5cfde2fe2235](https://jam.dev/c/4664a1f2-b622-40e3-bb1a-5cfde2fe2235)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by ChrisChasm** [comment]
Just make the Zúme in english not translatable.
