### ISSUE TITLE
Chinese - How to Follow Jesus Page

### ISSUE THREAD

**Issue by CE-Taiwan** [ZumeProject/zume-training-system#299]
When opening accordians, titles are in English.

Also...can we make it so you can also minimize the accordian if you click it again?

Watch the screen recording here: https://jam.dev/c/30b0a054-9fb8-490f-a79b-6e25946bdeb0

-------------------------------------

**Website URL:**
[https://zume5.training/zhtw/how-to-follow-jesus](https://zume5.training/zhtw/how-to-follow-jesus)

**Device and browser info:**
Chrome 124.0.6367.62 (1551x996) | Mac OS (arm) 10.15.7

**Date and time:**
April 23rd 2024 | 9:00am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/30b0a054-9fb8-490f-a79b-6e25946bdeb0](https://jam.dev/c/30b0a054-9fb8-490f-a79b-6e25946bdeb0)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
resolved by PR #458
