### ISSUE TITLE
Chinese- Training Page - text size

### ISSUE THREAD

**Issue by CE-Taiwan** [ZumeProject/zume-training-system#300]
Make the header text in the blue bars larger.  More prominent.

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/513cf280567ec9ac66d23baebe00507e/screenshot/db5b90c8-0495-446b-a67a-acef94622d23.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/513cf280567ec9ac66d23baebe00507e/screenshot/31f67481-4534-4ee8-9140-112af823f90e.png)

-------------------------------------

**Website URL:**
[https://zume5.training/zhtw/training/](https://zume5.training/zhtw/training/)

**Device and browser info:**
Chrome 124.0.6367.62 (1551x996) | Mac OS (arm) 10.15.7

**Date and time:**
April 23rd 2024 | 9:04am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/4dd92c2f-c86c-4566-80ed-ec31629ca12b](https://jam.dev/c/4dd92c2f-c86c-4566-80ed-ec31629ca12b)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
fixed on 372d608
