### ISSUE TITLE
Chinese Training Page - Button Allignment

### ISSUE THREAD

**Issue by CE-Taiwan** [ZumeProject/zume-training-system#301]
3 Session type buttons - Bottom one is out of alignment.

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/7e2cd20404be48bed0169cde9f6293b0/screenshot/bb00405c-ef21-4562-88fc-456dab4d9104.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/7e2cd20404be48bed0169cde9f6293b0/screenshot/21d04ce9-8f15-4b7f-afe4-e395e6df364f.png)

-------------------------------------

**Website URL:**
[https://zume5.training/zhtw/training/](https://zume5.training/zhtw/training/)

**Device and browser info:**
Chrome 124.0.6367.62 (1551x996) | Mac OS (arm) 10.15.7

**Date and time:**
April 23rd 2024 | 9:07am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/df2bf6f7-e8db-478a-af6a-d6773c02cc05](https://jam.dev/c/df2bf6f7-e8db-478a-af6a-d6773c02cc05)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
fixed on 872df80
