### ISSUE TITLE
Chinese-Share page - text center allignment

### ISSUE THREAD

**Issue by CE-Taiwan** [ZumeProject/zume-training-system#302]
Align the tag line under the title.

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/86f9dec304b07333cbf19fc2e4997ad4/screenshot/3d293423-7c97-4004-b783-ed28def33d1b.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/86f9dec304b07333cbf19fc2e4997ad4/screenshot/bbdfb61d-d571-48ce-8d27-bcc357aff0db.png)

-------------------------------------

**Website URL:**
[https://zume5.training/zhtw/share](https://zume5.training/zhtw/share)

**Device and browser info:**
Chrome 124.0.6367.62 (1551x996) | Mac OS (arm) 10.15.7

**Date and time:**
April 23rd 2024 | 9:08am UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/675f299c-19ad-4ae9-810f-e25cde2211d6](https://jam.dev/c/675f299c-19ad-4ae9-810f-e25cde2211d6)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
fixed on 12effa1
