### ISSUE TITLE
Center and Auto Sense Screen for Video QR code

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#312]
For support of qr codes in books that link to online videos there is a dedicated video play page. 
Right now the video loads in the top of the page. 
It does not auto sense screen size and set max height or width in order to fit the video on the screen.
Change:
Add screen awareness for height and width.
Add center alignment to the video in portrait screens.

Watch the screen recording here: https://jam.dev/c/ae1b9679-da99-4736-9052-8caec09f27ff

-------------------------------------

**Website URL:**
[https://zume5.training/zume_app/video/?id=390639511](https://zume5.training/zume_app/video/?id=390639511)

**Device and browser info:**
Mobile Safari 16.6 (390x844) | iOS 16.6

**Date and time:**
April 25th 2024 | 3:29pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/ae1b9679-da99-4736-9052-8caec09f27ff](https://jam.dev/c/ae1b9679-da99-4736-9052-8caec09f27ff)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
fixed in 355605a
