### ISSUE TITLE
Video Thumbnail

### ISSUE THREAD

**Issue by CE-Taiwan** [ZumeProject/zume-training-system#335]
Current video screen color clashes with overall website design.  

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/323e54230c1039e107ffd4a5a40bfe11/screenshot/a7c897a5-526e-457a-969e-feb53ace5f33.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/323e54230c1039e107ffd4a5a40bfe11/screenshot/da181b7c-3625-4511-9e4a-8ae8f54281e7.png)

-------------------------------------

**Website URL:**
[https://zume5.training/](https://zume5.training/)

**Device and browser info:**
Chrome 124.0.6367.118 (1684x941) | Mac OS (arm) 10.15.7

**Date and time:**
May 2nd 2024 | 2:35pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/d8c64b48-7490-464d-a7fb-63a1748cb5e6](https://jam.dev/c/d8c64b48-7490-464d-a7fb-63a1748cb5e6)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by ChrisChasm** [comment]
![Image](https://github.com/ZumeProject/zume-training-system/assets/7318348/67fef5ab-426c-44b4-89c9-5d7673ddc60e)
