### ISSUE TITLE
Getting Started-Set Profile Tile

### ISSUE THREAD

**Issue by CE-Taiwan** [ZumeProject/zume-training-system#337]
In this tile view, there is no Green Checkmark to indicate completed.  Do we need new graphics for this? Or can it be added?

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/57f56927ad9c3eca9144fd61319e0134/screenshot/b43e8f2c-11b0-4947-a587-a0b2981682b4.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/57f56927ad9c3eca9144fd61319e0134/screenshot/27cb0f0c-3e36-4508-9cc9-feae2b90e1cd.png)

-------------------------------------

**Website URL:**
[https://zume5.training/dashboard/](https://zume5.training/dashboard/)

**Device and browser info:**
Chrome 124.0.6367.118 (1684x941) | Mac OS (arm) 10.15.7

**Date and time:**
May 2nd 2024 | 10:31pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/87d09eb8-60cd-4a6c-8747-18f894f428eb](https://jam.dev/c/87d09eb8-60cd-4a6c-8747-18f894f428eb)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by ChrisChasm** [comment]
This tweak is enough for the user review. We can add green check later

https://jam.dev/c/fd46f238-f404-465a-a199-fc11b329fde2
![a180f103-8f88-4f53-bb07-2cd42a633149](https://github.com/ZumeProject/zume-training-system/assets/7318348/dac3bdb4-1da2-4c69-bc6b-e91a531e9e1e)

**Comment by squigglybob** [comment]
@CE-Taiwan I can put a tick in there if you want.

If it would just involve using the existing tick and putting it somewhere on that tile it shouldn't need any new graphics
But
I would need a design of where you would like the tick to go.

**Comment by squigglybob** [comment]
One option could be something like this
![image](https://github.com/ZumeProject/zume-training-system/assets/9816214/8d9f03a4-1430-4295-9b16-cb3abc42c178)
