### ISSUE TITLE
How to Follow Jesus Page: Titles not translating

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#340]
How to Follow Jesus Page: Titles not translating. 

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/63eb90865f3b6a9722e24a507ffb6155/screenshot/35c6099d-9378-4e46-94df-0683ca8e17d0.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/63eb90865f3b6a9722e24a507ffb6155/screenshot/491d2646-ab9c-4566-872b-0c3b8dd9c66c.png)

-------------------------------------

**Website URL:**
[https://zume5.training/zhtw/how-to-follow-jesus](https://zume5.training/zhtw/how-to-follow-jesus)

**Device and browser info:**
Chrome 124.0.6367.119 (2056x1198) | Mac OS (arm) 10.15.7

**Date and time:**
May 5th 2024 | 5:01pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/fca201d4-6ec8-4e18-8b72-997fecbc3ebc](https://jam.dev/c/fca201d4-6ec8-4e18-8b72-997fecbc3ebc)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
fixed in PR #458
