### ISSUE TITLE
Presenter Menu: Switch Views

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#343]
Switch views is not intuitive in communication of what the button does. 
Can we have the button change language depending on state, and maybe even have a toggle switch verse a button.
If a button, can it say "Slide View" and "List View". When it always offers the inactive state.
If a toggle is possible, then call the toggle List View, and toggle it on or off.

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/acff691b46b8d4e0d70da12933a5d0c6/screenshot/ea2d68ad-5d97-48d9-90c2-8fcd5565eadb.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/acff691b46b8d4e0d70da12933a5d0c6/screenshot/4b005876-f994-4494-824f-24da2f2c3987.png)

-------------------------------------

**Website URL:**
[https://zume5.training/presenter?session=1&view=guide](https://zume5.training/presenter?session=1&view=guide)

**Device and browser info:**
Chrome 124.0.6367.119 (1061x1198) | Mac OS (arm) 10.15.7

**Date and time:**
May 5th 2024 | 5:36pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/04d08596-7af0-4543-b990-d5907361ef8e](https://jam.dev/c/04d08596-7af0-4543-b990-d5907361ef8e)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
fixed in 8d21a69
