### ISSUE TITLE
Modal top spacing issue

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#344]
The modal has gone from full screen to and full screen with a 40px top padding.

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/2d0c382415f4d4509c2dde4f9e94fda7/screenshot/d18d9df4-cd24-484a-a2cb-08a68096ed07.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/2d0c382415f4d4509c2dde4f9e94fda7/screenshot/f93393f7-f96a-44cf-8f9e-4a7a51ec40dd.png)

-------------------------------------

**Website URL:**
[https://zume5.training/dashboard](https://zume5.training/dashboard)

**Device and browser info:**
Chrome 124.0.6367.119 (2033x1331) | Mac OS (arm) 10.15.7

**Date and time:**
May 5th 2024 | 8:24pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/f3f82bdc-ff32-4045-97e4-bca7502f8a08](https://jam.dev/c/f3f82bdc-ff32-4045-97e4-bca7502f8a08)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
I think this has been fixed now
