### ISSUE TITLE
wizard: add persuasive text for giving personal data

### ISSUE THREAD

**Issue by squigglybob** [ZumeProject/zume-training-system#347]
use reworded text from privacy policy in the expanded box when they click on ? to find out why we want location/phone data

(in wizard when asking for phone and location)

**Comment by ChrisChasm** [comment]
This was added at the bottom of the dashboard.php translations section. 

![Image](https://github.com/ZumeProject/zume-training-system/assets/7318348/df14d4f5-621c-4001-b72b-6f5aa1e35b9d)
