### ISSUE TITLE
Send Resource to /resource

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#349]
Instead of a modal pop up, let's send resources to the resources page @ /resources

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/9dd7768d96d24a88fc29d113dd8f6143/screenshot/a34f7858-6d57-47e7-8b1c-ca32a317b9b6.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/9dd7768d96d24a88fc29d113dd8f6143/screenshot/1ae70677-71e2-4840-a2ad-a0e408467f14.png)

-------------------------------------

**Website URL:**
[https://zume5.training/dashboard/](https://zume5.training/dashboard/)

**Device and browser info:**
Chrome 124.0.6367.119 (2150x1224) | Mac OS (arm) 10.15.7

**Date and time:**
May 8th 2024 | 8:18pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/4fcb4190-19c2-4667-9ac6-149fb18d8830](https://jam.dev/c/4fcb4190-19c2-4667-9ac6-149fb18d8830)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
closed by #392
