### ISSUE TITLE
Filter All Non-Complete Languages

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#362]
Every language that does not have pieces, need to those sections of the website not-accessible.

**Comment by squigglybob** [comment]
😅 
@ChrisChasm Do you mean that languages without pieces pages
1. should be totally filtered out?
or
2. Any parts of the site that involve pieces pages should be filtered out? 

If it's 2. then that should already be done

**Comment by ChrisChasm** [comment]
It's 2. 
This is done. Great!
