### ISSUE TITLE
Wizard Bug: Date dropdown

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#365]
Date drop down is not working in the wizard for scheduling a plan.

Watch the screen recording here: https://jam.dev/c/cbe1766a-24a2-4770-a4d9-f5c0e03a7f70

-------------------------------------

**Website URL:**
[https://zume5.training/wizard/getting-started/what-start-date](https://zume5.training/wizard/getting-started/what-start-date)

**Device and browser info:**
Chrome 124.0.6367.209 (2056x1198) | Mac OS (arm) 10.15.7

**Date and time:**
May 21st 2024 | 2:25pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/cbe1766a-24a2-4770-a4d9-f5c0e03a7f70](https://jam.dev/c/cbe1766a-24a2-4770-a4d9-f5c0e03a7f70)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
I think it does work, but you have to click on the invisible button on the very right.

I will try and get the button to show up on a white background
