### ISSUE TITLE
My Progress: Checkoff credit bug

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#371]
Two things:
I would love to color credit a persons click as soon as they click, before the REST returns a success, and then hand error returns as a secondary issue. This will make it feel snappier for the user no matter the bandwidth. 
Also, there is some bug keeping previous credit for a deeper progress click on the first half dozen list items. The video shows some of the lower training items are giving proper credit, but the first dozen are not. ??

Watch the screen recording here: https://jam.dev/c/151da132-e1b9-4b7b-94f8-4d9fa8ea6f03

-------------------------------------

**Website URL:**
[https://zume5.training/dashboard/my-progress](https://zume5.training/dashboard/my-progress)

**Device and browser info:**
Chrome 124.0.6367.209 (1683x1198) | Mac OS (arm) 10.15.7

**Date and time:**
May 21st 2024 | 3:06pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/151da132-e1b9-4b7b-94f8-4d9fa8ea6f03](https://jam.dev/c/151da132-e1b9-4b7b-94f8-4d9fa8ea6f03)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
good spot. I'll add

- [ ] color item immediately
- [ ] if fails, remove color and alert with warning banner
- [ ] fix bug where first items don't auto credit
