### ISSUE TITLE
My Progress: Info Button Bug

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#372]
When I click the info icon, I'm gettting a 3-month plan hangover from some previous activity.

Watch the screen recording here: https://jam.dev/c/15cb2e09-619c-4f0e-8ded-16da6a6aaff6

-------------------------------------

**Website URL:**
[https://zume5.training/dashboard/my-progress](https://zume5.training/dashboard/my-progress)

**Device and browser info:**
Chrome 124.0.6367.209 (1683x1198) | Mac OS (arm) 10.15.7

**Date and time:**
May 21st 2024 | 3:08pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/15cb2e09-619c-4f0e-8ded-16da6a6aaff6](https://jam.dev/c/15cb2e09-619c-4f0e-8ded-16da6a6aaff6)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
accidentally pushed to main without  PR
