### ISSUE TITLE
My Maps: Unlocked: Placeholder needed

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#373]
Let's put an iframe placeholder here for now. We can impove it later, but casting vision for saturation is part of the big picture. I feel like muting it removes too much for the vision. 
100 Hour Map can open modal iframe of 
https://zume.training/coaching/zume_app/last100_hours/
Training Vision Map can open modal iframe of
https://zume.training/coaching/zume_app/heatmap_practitioner/
Simple Church Planting Map can open modal iframe of 
https://zume.training/coaching/zume_app/heatmap_churches/

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/616bf369230ff2a1ee6fecd2e2a966ce/screenshot/83e5fc47-4707-456e-bf72-34daa2662a55.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/616bf369230ff2a1ee6fecd2e2a966ce/screenshot/56e49e85-42a8-4aa9-9b86-6f83f8135445.png)

-------------------------------------

**Website URL:**
[https://zume5.training/dashboard/my-maps](https://zume5.training/dashboard/my-maps)

**Device and browser info:**
Chrome 124.0.6367.209 (1683x1198) | Mac OS (arm) 10.15.7

**Date and time:**
May 21st 2024 | 3:18pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/7e4f6e33-f4a3-490a-b969-bebe7b8d244e](https://jam.dev/c/7e4f6e33-f4a3-490a-b969-bebe7b8d244e)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
added to main
