### ISSUE TITLE
Wizard: Contact Preference: Check box style

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#375]
The black box checkbox does not seem like the correct style of checkbox for the site. Could we use the checkbox style from Training list or My Plans and use that style here in this form?

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/6ed3ca555a2a57e366213724477cbe52/screenshot/24717369-fe4e-40c3-b83b-ed489fef6075.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/6ed3ca555a2a57e366213724477cbe52/screenshot/4d145966-dda4-48d9-bd84-8da95aa5d9b5.png)

-------------------------------------

**Website URL:**
[https://zume5.training/dashboard/my-coach](https://zume5.training/dashboard/my-coach)

**Device and browser info:**
Chrome 124.0.6367.209 (1683x1198) | Mac OS (arm) 10.15.7

**Date and time:**
May 21st 2024 | 3:23pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/6e81642e-9e3b-4536-a955-0b963ff9cc32](https://jam.dev/c/6e81642e-9e3b-4536-a955-0b963ff9cc32)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
fixed on 555a1d1
