### ISSUE TITLE
CTA: Submit Report: 404 error

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#378]
Let's mute the Submit Report CTA until post-go live. 

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/cf53e8100ee87695cb7824cb0d0a415b/screenshot/552d9934-6a71-4c1d-809b-fc19fc1a22a8.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/cf53e8100ee87695cb7824cb0d0a415b/screenshot/feb1dd5b-96b9-4d76-892c-90bda23ade0e.png)

-------------------------------------

**Website URL:**
[https://zume5.training/submit-report](https://zume5.training/submit-report)

**Device and browser info:**
Chrome 124.0.6367.209 (1683x1198) | Mac OS (arm) 10.15.7

**Date and time:**
May 21st 2024 | 3:32pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/e18a9782-b9dd-424b-9df6-74eb1ebd960d](https://jam.dev/c/e18a9782-b9dd-424b-9df6-74eb1ebd960d)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
fixed on main
