### ISSUE TITLE
CTA: Add Join Hub/Join Community challenge

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#386]
This CTA was removed for GO-Live but should be added back in parallel with investments to the community section.

**Screenshot:**
![jam-screenshot](https://cdn-jam-screenshots.jam.dev/e1f0dd6d9d1d6b52af83501228563124/screenshot/f0bacc01-8bba-4ff1-9319-145168acd40a.png)

**Full screen:**
![jam-full-url-screenshot](https://cdn-jam-screenshots.jam.dev/e1f0dd6d9d1d6b52af83501228563124/screenshot/69077bb5-c664-4c63-b3fe-4a3de163a071.png)

-------------------------------------

**Website URL:**
[https://zume5.training/dashboard/](https://zume5.training/dashboard/)

**Device and browser info:**
Chrome 124.0.6367.209 (2056x1198) | Mac OS (arm) 10.15.7

**Date and time:**
May 21st 2024 | 3:59pm UTC

**View developer information (console logs, network requests & timing):**
[jam.dev/c/a57cd811-82e2-45b4-9fa3-b40d69fe3f8f](https://jam.dev/c/a57cd811-82e2-45b4-9fa3-b40d69fe3f8f)

-------------------------------------

*Captured with* *[jam.dev](https://jam.dev?utm_source=github&utm_medium=integration&utm_campaign=captured_with_link_2022_11)*

**Comment by squigglybob** [comment]
fixed on main
