### ISSUE TITLE
GDPR Erase Account

### ISSUE THREAD

**Issue by squigglybob** [ZumeProject/zume-training-system#39]
will want to hand hold this process to make sure that the correct stuff gets redacted rather than being deleted.

e.g.
lng/lat coords being redacted to the closest grid_id

- [ ] remove user from firebase if they were using SSO

**Comment by ChrisChasm** [comment]
I think we can add a request for GDPR data wizard and link it to the privacy page. 
The wizard would make a request to the coaching system for administrators to respond too.
