### ISSUE TITLE
slides: generate offline slides for each language

### ISSUE THREAD

**Issue by squigglybob** [ZumeProject/zume-training-system#514]
Doing  english took 1-1.5 hours unscripted

**Comment by ChrisChasm** [comment]
This needs to be done with the correct auto generated urls inside the QR Codes. Just FYI.

**Comment by ChrisChasm** [comment]
English first

**Comment by ChrisChasm** [comment]
English created.

**Comment by ChrisChasm** [comment]
https://storage.googleapis.com/zume-file-mirror/en/zume-10-session-en.key
