### ISSUE TITLE
pieces: 3-gospel.png is broken

### ISSUE THREAD

**Issue by squigglybob** [ZumeProject/zume-training-system#549]

**Comment by ChrisChasm** [comment]
I have added a 3-circles presentation image. Was this what this was referring to?

Added 3-Circles Shortcode	96decdf	Chris Chasm <chris@chasm.solutions>	Jul 5, 2024 at 11:01 AM

**Comment by squigglybob** [comment]
I think so yeah.

**Comment by squigglybob** [comment]
We can double check
