### ISSUE TITLE
Question: should date be gmdate?

### ISSUE THREAD

**Issue by squigglybob** [ZumeProject/zume-training-system#570]
I have so far added `// phpcs:ignore` on lines where phpcs complains about usage of `date` function.

Should we ignore it or change to `gmdate` as it suggests?

What are the consequences to the backend of doing that?

gmdate will create formatted date strings based on Grenwich mean time instead of the server's local datetime

**Comment by ChrisChasm** [comment]
Yes. I think we're supposed to do that. I've seen warnings. (Confession: I might still naturally write date() when I'm thinking about the problem not the grammar.)

**Comment by ChrisChasm** [comment]
7955b11
