### ISSUE TITLE
Fix the commitment Question/Answer vs Note

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#593]
Question/Answer is only for the 3-Month plan.
Note is for all other plans and commitments. 

## todo

- [x] dash-plans to only create custom commitments with note
- [x] when editing a commitment load the correct data into the edit form (custom --> note, post_training_plan --> answer {with question in a <p> })

**Comment by squigglybob** [comment]
I'll need a 5 min chat to clarify what needs to change UX wise to match this
