### ISSUE TITLE
PostCut: Add/Confirm Google Analytics

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#603]

**Comment by squigglybob** [comment]
https://umami.gospelambition.com/teams/2d73ece1-4329-45a9-bfd8-d68f0acfc929/websites/e503fecf-00f2-4556-a7e3-40dd2671bdac

**Comment by squigglybob** [comment]
We have analytics running here. We just need to check that it is giving the data that we want
