### ISSUE TITLE
https://zume.training/the-gospel-and-how-to-share-it not working

### ISSUE THREAD

**Issue by squigglybob** [ZumeProject/zume-training-system#610]

**Comment by ChrisChasm** [comment]
![Image](https://github.com/user-attachments/assets/1384741e-1e54-4433-abde-2f96b4d7eeed)

**Comment by ChrisChasm** [comment]
I can confirm the database records are right. 
Why would notifications be called just for this page. And why do we need foundations and shared-functions?



![Image](https://github.com/user-attachments/assets/fb85ffb7-1bf0-4c99-8dc3-c30bb2dd57f7)

**Comment by squigglybob** [comment]
fixed on 63be0c99

It was the share page also trying to load it's magic linkness and having wp_head twice in the header 😬 

thanks @corsacca
