### ISSUE TITLE
Bug: Error trying to connect with a coach

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#613]
![Image](https://github.com/user-attachments/assets/fb14dc4a-69a4-4b3b-a687-b6be8fcdec01)

A: "I got this error when trying to connect with a coach. Is it because I selected telegram?"

Mac using Google Chrome

**Comment by squigglybob** [comment]
what wizard are you in?

**Comment by ChrisChasm** [comment]
I think we fixed.
