### ISSUE TITLE
Error: Password reset error

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#615]
Password reset link from login

![Image](https://github.com/user-attachments/assets/b52a4afa-38a7-4f5a-b260-eb1d50c58cdb)

Email received and link looks complete, but the page response is invalid key.

![Image](https://github.com/user-attachments/assets/df71710f-8fe4-40a2-bfed-e315dcfb466c)

Attempt to reset password from fail screen, and it returns broken reset page.

![Image](https://github.com/user-attachments/assets/f198f950-21df-4b48-90ba-b787a72d58e3)

On Mac and Chrome.

**Comment by squigglybob** [comment]
The first issue, appears to be a caching issue with object caching pro.

The second critical error is fixed on a3cbd25f
