### ISSUE TITLE
Bug: CTA for sharing concept sends to english, not selected language.

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#616]
![Image](https://github.com/user-attachments/assets/500f9dee-9b6a-47f4-9b90-c7e90dc06744)

![Image](https://github.com/user-attachments/assets/e0778cf1-e17b-4d8c-9780-5624563f6fee)

**Comment by squigglybob** [comment]
fixed on c6ddd139

The HOST sharing CTAs aren't built out yet, so just muted the 2 that were in there for now
