### ISSUE TITLE
Registration: Add disable and spinner to button once submitted.

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#631]
![Image](https://github.com/user-attachments/assets/adeb3a2e-ac1e-457b-a972-fd17901bfc1f)

There is a delay after registering, but there is no spinner or color change in the button. We should add a processing indicator to save people with slow connections from reclicking or abandoning.

**Comment by squigglybob** [comment]
fixed on 4c19a5a4
