### ISSUE TITLE
Upgrade the checking landing page.

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#632]
## Nath's todo list

- [x] show celebration modal on landing on the dashboard which fades away by itself
- [x] adjust nav to only show my progress
- [x] add white bar seperators to progress bar
- [x] Show all progress
- [x] scroll to last week's section
- [x] toggle host elements on click
- [x] check that checking in checks off host elements
- [x] check that checking in lands in correct language

## The problem
![Image](https://github.com/user-attachments/assets/f51f4940-3110-432c-b325-1fa878428738)

Design upgrade for landing page. 

Primarily I think this page needs to inform/connect people with their progress and vision for what is next. Maybe show an abbreviated progress checklist.

**Comment by squigglybob** [comment]
We want to create the link between checking in and ticking off heard in progress list

**Comment by squigglybob** [comment]
@CE-Taiwan  This needs some discussion and design

**Comment by squigglybob** [comment]
Also the progress % needs to be updated based on what they have heard, rather than which session it is.
