### ISSUE TITLE
Polish the CTA System

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#657]
Confirm all CTAs are showing up at the right stage.
Confirm all CTSs link to destination correctly.

##  nath's todos

- [x] join online training
- [x] request a coach
- [ ] join community
- [x] create training
- [x] set profile
- [x] create 3 month plan
- [x] complete 3 month plan

**Comment by squigglybob** [comment]
https://www.loom.com/share/bb1f861917f64b08b6ec8d0f9061c635
