### ISSUE TITLE
Disable all default notification/emails

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#7]
https://loom.com/share/a938ee7bf62a4140b08f8ce3c2a1f66f?sid=ba2b40ac-ae12-4088-955f-f94de5b25dc9

- [x] disable all WP email notifications
- [x] disable all DT email notifications
- [x] let Zume emails through the email embargo

links with https://github.com/ZumeProject/zume-system-patches/pull/1

**Comment by squigglybob** [comment]
@ChrisChasm 

This code is in the zume-patches under z-trainer.
What needs to happen differently to this.

Is it that this is too sledgehammery as it just disables all emails,
and we want to be able to let through only emails that we want to send through?

```php
add_filter('dt_block_development_emails', 'zume_system_patches_disable_dt_email' );
function zume_system_patches_disable_dt_email(){
    dt_write_log( __METHOD__ );
    return true;
}


add_filter('wp_mail','zume_system_patches_disable_wp_emails', 10,1);
function zume_system_patches_disable_wp_emails( $args ){
    dt_write_log( __METHOD__ );
    dt_write_log( $args );
    unset ( $args['to'] );
    return $args;
}

add_action( 'init', 'wp_disable_new_user_notifications' );
function wp_disable_new_user_notifications() {
    remove_action( 'register_new_user', 'wp_send_new_user_notifications' );
    remove_action( 'edit_user_created_user', 'wp_send_new_user_notifications', 10, 2 );
}
```

**Comment by squigglybob** [comment]
I have gone with using an email header to allow Zume email through using the pre_wp_mail hook to stop non zume emails
