### ISSUE TITLE
Request: Order and archive multiple trainings list

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#714]
- [x] Add to the multiple trainings list the capacity to change status and archive. 
- [x] Also, order the list newest to oldest. 
- [x] Also, add key to tagging in coaching and add link to tagged group

![Image](https://github.com/user-attachments/assets/5a947932-a179-4403-a256-3e125aea1ce1)

![Image](https://github.com/user-attachments/assets/5ffa134e-bb36-4a52-83ff-b0545182fbdf)

**Comment by squigglybob** [comment]
When users join a coaches group, add the group join_key as a tag on their coaching contact...
