### ISSUE TITLE
Alt video option for countries that don't support Vimeo.

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#744]
We need to maintain a small list of countries that do not support Vimeo delivery, Indonesia is one. And provide and alternate HTML5 direct video delivery from Google Cloud .mp4 files. 

## Nath's checklist
- [x] check if vimeo.com is available with a GET on first site load and store in a session cookie
- [x] use this to switch between showing vimeo and showing html5
- [ ] Check this works correctly using protonVPN
- [ ] add button 'Video broken?' to switch to the html5 version
- [x] switch all videos in anon section to use video tag based on the altVideo check

**Comment by squigglybob** [comment]
Targeting by language only would be brute force as it doesn't take into account their location.

If we could know how teh video fails, we could listen and auto load the html5 version.

OR

We could offer a 'Video broken?' button that when clicked loads the html5 versions instead

Vimeo adds
* quality 
* transfer rates
* dropping resolutions
* subtitles
*
