### ISSUE TITLE
Create user profile page for profile management

### ISSUE THREAD

**Issue by ChrisChasm** [ZumeProject/zume-training-system#9]
https://www.loom.com/share/ca25cc24708843e1b7d1c5dbf47500ac?sid=fc735ec1-6190-448d-a7bf-81f4805391c3

- [x] add /profile magic link page
- [x] replicate functionality of zume profile page
  - [x] ability to change user meta for name, number, location etc.
- [x] give the new user the multiplier role

## On server

- [x] update theme
- [x] change default role to multiplier

**Comment by squigglybob** [comment]
In dt-users there is an example of how a template is pulled from a non standard location.
